import 'package:hive/hive.dart';

part 'word.g.dart'; // This will be generated by Hive

@HiveType(typeId: 0) // Unique ID for your class
class Word extends HiveObject {
  @HiveField(0)
  String word;

  @HiveField(1)
  String definition;

  Word({required this.word, required this.definition});
}

